"""Faculty class report: end-to-end check against a real record generated by a built module.

Run from the hub folder with a built PALS module beside it:
    python tests/test_report.py [path/to/module/index.html]
"""
import json, os, sys, tempfile
from playwright.sync_api import sync_playwright

HUB = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MOD = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(HUB), "pals", "index.html")
url = lambda p: "file:///" + os.path.abspath(p).replace("\\", "/").lstrip("/")
REPORT, HUBIDX = url(os.path.join(HUB, "class-report.html")), url(os.path.join(HUB, "index.html"))
fails = []
def check(n, c, x=""):
    print(("  OK   " if c else "  FAIL ") + n + ((" :: " + str(x)) if x and not c else ""))
    if not c: fails.append(n)

SEED = """try{var K='vkp.pals2025.v4';var s={v:1,items:{},prefs:{pri:'all',lvl:'x',set:'both',fs:'m',theme:'system'},
placement:null,lastUnit:null,exam:{attempts:[],lockUntil:0},settings:null,started:Date.now(),
profile:{name:'Test Learner',institution:'Report Test College',reg:'RT-001',email:'',enrolledAt:Date.now()},plan:null,onboarded:true};
if(!localStorage.getItem(K)) localStorage.setItem(K,JSON.stringify(s));}catch(e){}"""

CONTRAST_JS = r"""()=>{
 function rgb(s){const m=s.match(/[\d.]+/g); return m?m.map(Number):[0,0,0,0];}
 function L(c){const a=c.slice(0,3).map(v=>{v/=255;return v<=0.03928?v/12.92:Math.pow((v+0.055)/1.055,2.4)});return 0.2126*a[0]+0.7152*a[1]+0.0722*a[2];}
 function bg(el){while(el){const c=rgb(getComputedStyle(el).backgroundColor); if(c.length<4||c[3]>0.5) return c; el=el.parentElement;} return [255,255,255];}
 const bad=[];
 document.querySelectorAll('body *').forEach(el=>{
  if(![...el.childNodes].some(n=>n.nodeType===3&&n.textContent.trim())) return;
  const r=el.getBoundingClientRect(); if(!r.width||!r.height) return;
  const cs=getComputedStyle(el); if(cs.visibility==='hidden'||el.closest('.sr-only,.hidden,[hidden]')) return;
  const f=rgb(cs.color), b=bg(el), l1=L(f), l2=L(b), cr=(Math.max(l1,l2)+0.05)/(Math.min(l1,l2)+0.05);
  const big=parseFloat(cs.fontSize)>=24||(parseFloat(cs.fontSize)>=18.6&&+cs.fontWeight>=700);
  if(cr<(big?3:4.5)) bad.push(el.tagName+'.'+el.className+' '+cr.toFixed(2)+' "'+el.textContent.trim().slice(0,30)+'"');
 }); return bad;}"""

with sync_playwright() as pw, tempfile.TemporaryDirectory() as tmp:
    b = pw.chromium.launch()
    ctx = b.new_context(viewport={"width": 1280, "height": 900}, accept_downloads=True, reduced_motion="reduce")
    ctx.add_init_script(SEED)
    net, errs = [], []
    ctx.on("request", lambda r: net.append(r.url) if not r.url.startswith(("file:", "data:", "blob:")) else None)

    print("\n== REAL RECORD FROM THE MODULE ==")
    p = ctx.new_page(); p.on("pageerror", lambda e: errs.append("module: " + str(e)))
    p.goto(url(MOD)); p.wait_for_timeout(900)
    def ans(q, right, conf):
        p.evaluate("""([q,r,c])=>{const n=document.querySelector('.q[data-q="'+q+'"]');
          n.querySelector('.conf button[data-cf="'+c+'"]').click();
          const b=n.querySelector(r?'.opt[data-c="1"]':'.opt:not([data-c="1"])'); if(b&&!b.disabled) b.click();}""", [q, right, conf])
        p.wait_for_timeout(120)
    p.evaluate("()=>document.querySelector('#u1 .unit-head').click()")
    ans("1.1", False, "s"); ans("1.2", True, "s"); ans("2.1", True, "f"); ans("2.2", False, "g")
    p.wait_for_timeout(700)
    with p.expect_download() as d:
        p.evaluate("()=>document.getElementById('dlRecord').click()")
    rec_path = os.path.join(tmp, "real.json"); d.value.save_as(rec_path)
    rec = json.load(open(rec_path))
    check("module record is format 2 with detail", rec.get("formatVersion") == 2 and len(rec["detail"]["units"]) == 20)
    u1 = rec["detail"]["units"][0]; u2 = rec["detail"]["units"][1]
    check("unit 1 detail: seen 2, right first 1, 1 miss, 1 confident-wrong",
          (u1["firstSeen"], u1["firstRight"], u1["misses"], u1["cw"]) == (2, 1, 1, 1), u1)
    check("unit 2 detail: seen 2, right first 1, no confident-wrong (guess)",
          (u2["firstSeen"], u2["firstRight"], u2["cw"]) == (2, 1, 0), u2)
    check("calibration carried (sure 1 right / 1 wrong)", rec["detail"]["calibration"]["sure"] == [1, 1], rec["detail"]["calibration"])

    # Passport from the hub (same file:// storage)
    h = ctx.new_page(); h.on("pageerror", lambda e: errs.append("hub: " + str(e)))
    h.goto(HUBIDX); h.wait_for_timeout(700)
    check("hub links to the class report", h.evaluate("()=>!!document.querySelector('a[href=\"class-report.html\"]')"))
    with h.expect_download() as d2:
        h.click("#ppExport")
    pp_path = os.path.join(tmp, "passport.json"); d2.value.save_as(pp_path)

    # Tampered copies + junk
    t1 = dict(rec); t1["result"] = dict(rec["result"], bestScore=99); t1["learner"] = dict(rec["learner"], name="Tampered Score", registration="RT-002")
    t2 = json.loads(json.dumps(rec)); t2["detail"]["units"][0]["misses"] = 0; t2["learner"]["name"] = "Tampered Detail"
    t2["learner"]["registration"] = "RT-003"
    # t2 core checksum covers the name, so recompute nothing: expect core 'Changed' too — build a detail-only tamper instead
    t3 = json.loads(json.dumps(rec)); t3["detail"]["units"][0]["misses"] = 0
    paths = {}
    for nm, obj in (("t1.json", t1), ("t3.json", t3)):
        paths[nm] = os.path.join(tmp, nm); json.dump(obj, open(paths[nm], "w"))
    junk = os.path.join(tmp, "junk.json"); open(junk, "w").write('{"hello":1}')
    trunc = os.path.join(tmp, "trunc.json"); open(trunc, "w").write(open(rec_path).read()[:200])

    print("\n== CLASS REPORT ==")
    r = ctx.new_page(); r.on("pageerror", lambda e: errs.append("report: " + str(e)))
    r.goto(REPORT); r.wait_for_timeout(500)
    check("empty state: summary hidden", r.evaluate("()=>document.getElementById('summaryCard').classList.contains('hidden')"))
    r.set_input_files("#files", [rec_path]); r.wait_for_timeout(400)
    rows = r.evaluate("()=>__VKP_REPORT__.rows()")
    check("real record ingested, integrity ok, detail ok", len(rows) == 1 and rows[0]["integ"] == "ok" and rows[0]["dInteg"] == "ok", rows and (rows[0]["integ"], rows[0]["dInteg"]))
    check("confident-and-wrong counted from detail", rows[0]["cw"] == 1, rows[0]["cw"])
    check("unit table shown for a single module", r.evaluate("()=>!document.getElementById('unitCard').classList.contains('hidden')"))
    top = r.evaluate("()=>document.querySelector('#ut tbody tr td').textContent")
    check("weakest unit at top is Unit 1 or 2 (50% first time)", top.startswith("1 ·") or top.startswith("2 ·"), top)

    r.set_input_files("#files", [paths["t1.json"], paths["t3.json"], junk, trunc]); r.wait_for_timeout(500)
    rows = {x["name"]: x for x in r.evaluate("()=>__VKP_REPORT__.rows()")}
    check("score tamper flagged as Changed", rows.get("Tampered Score", {}).get("integ") == "bad")
    check("detail-only tamper: kept newer duplicate, detail rejected",
          rows.get("Test Learner", {}).get("dInteg") == "bad" and rows["Test Learner"]["detail"] is None, rows.get("Test Learner", {}).get("dInteg"))
    warns = r.evaluate("()=>document.getElementById('warns').textContent")
    check("warnings name junk and truncated files", "junk.json" in warns and "trunc.json" in warns and "not valid JSON" in warns)
    check("duplicate warning shown", "Duplicate for Test Learner" in warns)
    check("integrity tile counts 1", "Integrity problems1" in r.evaluate("()=>document.getElementById('stats').textContent"),
          r.evaluate("()=>document.getElementById('stats').textContent"))

    r.set_input_files("#files", [pp_path]); r.wait_for_timeout(400)
    pr = [x for x in r.evaluate("()=>__VKP_REPORT__.rows()") if x["kind"] == "passport"]
    # Passport has the same reg (RT-001) + module → it is a duplicate of Test Learner's record and is newer
    allrows = r.evaluate("()=>__VKP_REPORT__.rows()")
    check("Passport checksum verified", "Passport checksum does not match" not in r.evaluate("()=>document.getElementById('warns').textContent"))
    check("Passport row merged as duplicate (no second Test Learner row)", sum(1 for x in allrows if x["reg"] == "RT-001") == 1)

    print("\n== SAMPLE BATCH ==")
    r.click("#clear"); r.wait_for_timeout(200)
    r.click("#sample"); r.wait_for_timeout(500)
    check("12 sample learners", r.evaluate("()=>__VKP_REPORT__.rows().length") == 12)
    top5 = r.evaluate("()=>[...document.querySelectorAll('#ut tbody tr')].slice(0,5).map(t=>parseInt(t.cells[0].textContent,10))")
    check("hard units (7,11,14,15,17) dominate the top five", len(set(top5) & {7, 11, 14, 15, 17}) >= 4, top5)
    check("sample records all pass integrity", r.evaluate("()=>__VKP_REPORT__.rows().every(x=>x.integ==='ok'&&x.dInteg==='ok')"))
    r.fill("#q", "Learner C"); r.wait_for_timeout(200)
    check("search filters the table", r.evaluate("()=>document.querySelectorAll('#lt tbody tr').length") == 1)
    r.fill("#q", ""); r.wait_for_timeout(150)
    r.evaluate("()=>document.querySelector('#lt th button[data-k=\"best\"]').click()"); r.wait_for_timeout(100)
    r.evaluate("()=>document.querySelector('#lt th button[data-k=\"best\"]').click()"); r.wait_for_timeout(100)
    check("sort by best exam descending", r.evaluate("()=>document.querySelector('#lt th[aria-sort=\"descending\"]')!==null"))
    with r.expect_download() as dl:
        r.click("#csvL")
    lp = os.path.join(tmp, "l.csv"); dl.value.save_as(lp); lcsv = open(lp, encoding="utf-8-sig").read().splitlines()
    check("learners CSV: header + 12 rows", len(lcsv) == 13 and lcsv[0].startswith("Name,Registration"), len(lcsv))
    with r.expect_download() as du:
        r.click("#csvU")
    up = os.path.join(tmp, "u.csv"); du.value.save_as(up); ucsv = open(up, encoding="utf-8-sig").read().splitlines()
    check("units CSV: header + 20 rows", len(ucsv) == 21, len(ucsv))

    print("\n== MEGACODES ==")
    NRPREC = os.environ.get("VKP_MEGA_RECORD")
    mrec = json.load(open(NRPREC)) if NRPREC and os.path.exists(NRPREC) else None
    if mrec and (mrec.get("detail") or {}).get("megacodes"):
        bad = json.loads(json.dumps(mrec)); bad["detail"]["megacodes"][0]["best"] = 100 if bad["detail"]["megacodes"][0]["best"] != 100 else 50
        bad["learner"] = dict(mrec["learner"]); mp = os.path.join(tmp, "mega.json"); bp = os.path.join(tmp, "megabad.json")
        json.dump(mrec, open(mp, "w")); json.dump(bad, open(bp, "w"))
        r.click("#clear"); r.wait_for_timeout(150)
        r.set_input_files("#files", [mp]); r.wait_for_timeout(400)
        row = r.evaluate("()=>__VKP_REPORT__.rows()[0]")
        check("megacode record: detail checksum verifies", row["dInteg"] == "ok", row["dInteg"])
        check("megacode record: %d cases carried" % len(mrec["detail"]["megacodes"]), row["mega"] and len(row["mega"]) == len(mrec["detail"]["megacodes"]))
        check("megacode card shown with one row per case", r.evaluate("()=>!document.getElementById('megaCard').classList.contains('hidden') && document.querySelectorAll('#mt tbody tr').length") == len(mrec["detail"]["megacodes"]))
        r.set_input_files("#files", [bp]); r.wait_for_timeout(400)
        row = r.evaluate("()=>__VKP_REPORT__.rows()[0]")
        check("tampered megacode score rejects the detail", row["dInteg"] == "bad", row["dInteg"])
    else:
        print("  (skipped: set VKP_MEGA_RECORD to a completion record that contains megacode runs)")
    r.click("#clear"); r.wait_for_timeout(150); r.click("#sample"); r.wait_for_timeout(400)
    check("sample batch shows the megacode table", r.evaluate("()=>document.querySelectorAll('#mt tbody tr').length") == 6)

    print("\n== MULTI-MODULE FILTER ==")
    r.evaluate("""()=>{const x=JSON.parse(JSON.stringify(%s)); __VKP_REPORT__.ingest(JSON.stringify(x),'real.json'); __VKP_REPORT__.render();}""" % json.dumps(rec))
    opts = r.evaluate("()=>[...document.querySelectorAll('#modSel option')].map(o=>o.value)")
    check("module filter lists All + 1 module id (sample shares pals2025)", opts[:1] == ["pals2025"] or "*" in opts, opts)

    print("\n== CONTRAST ==")
    for theme in ("light", "dark"):
        r.evaluate("t=>document.documentElement.setAttribute('data-theme',t)", theme); r.wait_for_timeout(150)
        bad = r.evaluate(CONTRAST_JS)
        check("contrast >= 4.5:1 (%s)" % theme, not bad, bad[:6])

    print("\n== MOBILE 390 px ==")
    m = ctx.new_page(); m.set_viewport_size({"width": 390, "height": 800}); m.on("pageerror", lambda e: errs.append("mobile: " + str(e)))
    m.goto(REPORT); m.wait_for_timeout(300); m.click("#sample"); m.wait_for_timeout(500)
    sw = m.evaluate("()=>document.documentElement.scrollWidth")
    check("no horizontal page scroll at 390 px", sw <= 390, sw)
    m.screenshot(path=os.path.join(HUB, "tests", "report-mobile.png"), full_page=False)
    r.set_viewport_size({"width": 1280, "height": 900}); r.evaluate("()=>document.documentElement.setAttribute('data-theme','light')")
    r.screenshot(path=os.path.join(HUB, "tests", "report-desktop.png"), full_page=True)

    check("no page errors", not errs, errs)
    check("no network requests", not net, net[:5])
    b.close()

print("\nFAILURES:", ", ".join(fails) if fails else "none")
